name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - run: https://github.com/features/actions/checkout@v2
      - run: https://github.com/features/actions/setup-node@v1
      - run: npm install -g bats
      - run: bats -v


